name: Build & push base image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    pull_requests:
      branches:
        - "main"

jobs:
  build:
    uses: magnuspihl/basic-env/.github/workflows/_build-and-push.yml@main
    with:
      image: base
